name: C++ Build and Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build with make
      run: |
        if make; then
          echo "Build successful"
          exit 0
        else
          echo "Build failed"
          exit 1
        fi
